REALMC-7121: Update Symbol so that they are unique
10gen/otto pull request #28
Opened 2020-11-12 16:14 UTC by asudhakal

2020-11-12 18:22 UTC, haleyowen commented
oopsies

2020-11-12 18:23 UTC, edaniels commented
Alright let’s bring in the b-team

2020-11-12 19:29 UTC, Gabri3l commented
lol hey guys!

2020-11-13 16:25 UTC, Gabri3l requested changes
😎  So excited for this fix!

A few small comments but overall I think this is the right direction!

2020-11-13 16:25 UTC, Gabri3l commented on builtin_json.go
> +					isSymbol := strings.HasPrefix(name, "Symbol(")
[optional] I would add a comment here that this will also skip object fields where the key has `"Symbol("` as a prefix and that we are making a compromise. All in all I think it'll be hard for a user to not only have manually set a key to be "Symbol(" but also needing to run `JSON.stringify` on that object.

2020-11-13 22:35 UTC, Gabri3l approved these changes
This looks good enough for me, thank you for adding the comments, I'm sure we will be very grateful for them in the future! 🚀

2020-11-18 01:08 UTC, tsedgwick approved these changes
LGTM once we get that test fixed 🙏🏻

2020-11-18 21:58 UTC, merged