REALMC-7122: add support for Array.Prototype.entries
10gen/otto pull request #29
Opened 2020-11-23 18:05 UTC by asudhakal

2020-11-23 18:17 UTC, tsedgwick commented on builtin_array.go
> +func builtinArray_entries(call FunctionCall) Value {
as we add more here, can we start validating that we have this functionality in https://github.com/mongodb-forks/goja on the `realm` branch?

2020-11-23 18:20 UTC, asudhakal commented on builtin_array.go
> +func builtinArray_entries(call FunctionCall) Value {
Yep, goja does have the `.entries` property for Arrays: https://github.com/mongodb-forks/goja/blob/realm/builtin_array.go#L1201

2020-11-23 18:22 UTC, tsedgwick commented on builtin_array.go
> +func builtinArray_entries(call FunctionCall) Value {
yeah just wanted to call it out for anything in the future to make sure we are cross referencing 🙂

2020-11-23 22:12 UTC, Gabri3l requested changes
💪 Nice work over here! Just one small thing to check that could go against the spec but other than that this looks wonderful!

2020-11-23 22:12 UTC, Gabri3l commented on builtin_array.go
> +			toValue_string(name),
[major] Make sure this first value returned by entries is an integer and not a string. You can even add a specific test for this, where you assign the first value of the tuple to a variable and make sure it's the integer `0`.

2020-11-24 16:46 UTC, Gabri3l approved these changes
:shipit: 

Remember to do a squash and merge or something like that, your last PR had all the commits merged instead of being just one (happened to me as well on another repo =D).

2020-11-24 16:57 UTC, merged